#!/bin/bash


PORT=
HOST=
while getopts ":p:h:H" opt; do
  case $opt in
    p)
      [[ ! "$OPTARG" =~ ^[0-9][0-9]*$ ]] && echo "Invalid port number. See $0 -H" >&2 && exit 1
      PORT=$OPTARG 
      ;;
    h)
      ping -c1 -W2 $OPTARG 1>/dev/null 2>/dev/null
      [ ! -z $? ] && echo "Invalid or unreachable host. See $0 -H" && exit 1 
      HOST=$OPTARG
      ;;
    H)
      echo "$0 - Show packet lost percentage."
      echo "Usage: $0 [ -h <host> -p <port> | -h <host> ]"
      echo "     -p <port>    Show SYN-ACK losts for SYN ping to <port>. (<host> is required.)"
      echo "     -h <host>    Ping target address. (Default is 8.8.8.8)"
      ;;
    \?)
      echo "Invalid option: -$OPTARG. See $0 -h" >&2 && exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument. See $0 -H" >&2 && exit 1
      ;;
  esac
done

[ ! -z "$PORT" -a -z "$HOST" ] && echo "Host is required when use -p. See $0 -H" && exit 1
[ -z "$HOST" ] && HOST="8.8.8.8"


echo PORT=$PORT HOST=$HOST
exit

addr="$1"
[ -z "$1" ] && addr="8.8.8.8"

echo Packet lost percentage for $addr

while [ 1=1 ]
do 
  lost=`ping -i.2 -c10 $addr | grep -Po "\d+%" | grep -Po "\d+"`
  echo -ne "$lost "; 
  for i in `seq 1 $((lost/3))`
  do 
    echo -ne "*"
  done
  echo 
done


